version: "3.7"

networks:
  slate:
    driver: bridge

services:
  app:
    build:
      args:
        user: jordan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: slate
    container_name: slate-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - slate

  nginx:
    image: nginx:alpine
    container_name: slate-nginx
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - slate